CREATE TYPE order_status as ENUM ('PROCESSING', 'COMPLETED', 'FAILED');

CREATE TABLE orders (
  id UUID NOT NULL PRIMARY KEY,
  item_id VARCHAR(255) NOT NULL,
  quantity INTEGER NOT NULL,
  status order_status NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
